---
apiVersion: v2
description: SmartIoT-config is an config system for SmartIoT Esp32/Esp8266 firmware helping for discovery, OTA upate and config backup.
name: smartiot-config
version: 0.1.0
maintainers:
  - name: AntorFR
    email: contact@antor.fr
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.4.2
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: First chart release
